import type { OneClawCapabilityDefinition } from '../types';

export const oneClawCapabilityRegistry: OneClawCapabilityDefinition[] = [
  {
    action: 'social.post',
    title: 'Publish to X',
    domain: 'social',
    capabilities: ['communicate', 'record', 'govern'],
    connectorKey: 'messaging_connector',
    maturity: 'production',
    liveMode: 'live',
    risk: 'high',
    approvalRequired: true,
    supportsDryRun: true,
    supportsRollback: false,
    inputRequired: ['channel', 'content'],
    outputContract: ['taskId', 'tweetId', 'status'],
    productionNote: 'Live X publishing is connected; every publish still needs approval or an explicit auto policy.',
  },
  {
    action: 'x.searchRecentTweets',
    title: 'Search X',
    domain: 'social',
    capabilities: ['research', 'monitor', 'record'],
    connectorKey: 'knowledge_connector',
    maturity: 'production',
    liveMode: 'live',
    risk: 'medium',
    approvalRequired: false,
    supportsDryRun: false,
    supportsRollback: false,
    inputRequired: ['query'],
    outputContract: ['tweets', 'status'],
    productionNote: 'Read-only X research can feed monitoring, research, and content workflows.',
  },
  {
    action: 'browser.open',
    title: 'Open Browser Page',
    domain: 'browser',
    capabilities: ['operate', 'research', 'record'],
    connectorKey: 'browser_connector',
    maturity: 'guarded',
    liveMode: 'live',
    risk: 'medium',
    approvalRequired: false,
    supportsDryRun: false,
    supportsRollback: false,
    inputRequired: ['url'],
    outputContract: ['url', 'status'],
    productionNote: 'Browser actions are useful for web operations, but selectors and logged-in sessions need runtime guards.',
  },
  {
    action: 'browser.extract',
    title: 'Extract Web Content',
    domain: 'browser',
    capabilities: ['research', 'operate', 'record'],
    connectorKey: 'browser_connector',
    maturity: 'guarded',
    liveMode: 'live',
    risk: 'medium',
    approvalRequired: false,
    supportsDryRun: false,
    supportsRollback: false,
    inputRequired: ['url'],
    outputContract: ['text', 'html', 'screenshotPath'],
    productionNote: 'Good candidate for research and monitoring once page failures are reconciled into proof.',
  },
  {
    action: 'api.request',
    title: 'Call External API',
    domain: 'api',
    capabilities: ['integrate', 'operate', 'record'],
    connectorKey: 'operations_connector',
    maturity: 'guarded',
    liveMode: 'live',
    risk: 'medium',
    approvalRequired: false,
    supportsDryRun: true,
    supportsRollback: false,
    inputRequired: ['url', 'method'],
    outputContract: ['ok', 'status', 'body'],
    productionNote: 'API execution should use allowlists, secret redaction, and response-status checks.',
  },
  {
    action: 'message.send',
    title: 'Send Telegram Message',
    domain: 'messaging',
    capabilities: ['communicate', 'coordinate', 'record'],
    connectorKey: 'messaging_connector',
    maturity: 'guarded',
    liveMode: 'live',
    risk: 'high',
    approvalRequired: true,
    supportsDryRun: true,
    supportsRollback: false,
    inputRequired: ['text'],
    outputContract: ['messageId', 'status'],
    productionNote: 'Use for operator notifications and approval loops before broader messaging providers are added.',
  },
  {
    action: 'file.write',
    title: 'Write File',
    domain: 'file',
    capabilities: ['operate', 'create', 'record'],
    connectorKey: 'file_connector',
    maturity: 'guarded',
    liveMode: 'live',
    risk: 'medium',
    approvalRequired: true,
    supportsDryRun: true,
    supportsRollback: true,
    inputRequired: ['path', 'content'],
    outputContract: ['path', 'bytesWritten'],
    productionNote: 'Production use needs workspace allowlists and overwrite protection.',
  },
  {
    action: 'code.workspace.status',
    title: 'Inspect Code Workspace',
    domain: 'code',
    capabilities: ['operate', 'research', 'record'],
    connectorKey: 'file_connector',
    maturity: 'guarded',
    liveMode: 'live',
    risk: 'low',
    approvalRequired: false,
    supportsDryRun: false,
    supportsRollback: false,
    inputRequired: [],
    outputContract: ['status', 'workspacePath', 'git', 'files'],
    productionNote: 'Read-only code workspace inspection can run automatically when a workspace is configured.',
  },
  {
    action: 'code.diff.prepare',
    title: 'Prepare Code Diff',
    domain: 'code',
    capabilities: ['create', 'operate', 'govern', 'record'],
    connectorKey: 'file_connector',
    maturity: 'guarded',
    liveMode: 'live',
    risk: 'medium',
    approvalRequired: false,
    supportsDryRun: true,
    supportsRollback: false,
    inputRequired: ['objective'],
    outputContract: ['summary', 'diff', 'files', 'status'],
    productionNote: 'Diff preparation is preview-only. TheOne should show the patch before any file mutation.',
  },
  {
    action: 'code.patch.apply',
    title: 'Apply Code Patch',
    domain: 'code',
    capabilities: ['operate', 'govern', 'record'],
    connectorKey: 'file_connector',
    maturity: 'guarded',
    liveMode: 'live',
    risk: 'high',
    approvalRequired: true,
    supportsDryRun: false,
    supportsRollback: true,
    inputRequired: ['patch'],
    outputContract: ['status', 'files', 'receipt'],
    productionNote: 'Applying a patch mutates a workspace and must remain approval-gated with proof.',
  },
  {
    action: 'construction.task.create',
    title: 'Create Construction Task',
    domain: 'construction',
    capabilities: ['coordinate', 'operate', 'record'],
    connectorKey: 'operations_connector',
    maturity: 'planned',
    liveMode: 'prepared',
    risk: 'medium',
    approvalRequired: false,
    supportsDryRun: true,
    supportsRollback: false,
    inputRequired: ['title'],
    outputContract: ['tracked', 'payload'],
    productionNote: 'Currently returns structured construction records; connect a real construction backend before live field execution.',
  },
  {
    action: 'construction.approval.request',
    title: 'Request Construction Approval',
    domain: 'construction',
    capabilities: ['coordinate', 'govern', 'record'],
    connectorKey: 'operations_connector',
    maturity: 'planned',
    liveMode: 'prepared',
    risk: 'high',
    approvalRequired: true,
    supportsDryRun: true,
    supportsRollback: false,
    inputRequired: ['title', 'projectId'],
    outputContract: ['approvalRequested', 'tracked'],
    productionNote: 'Useful as a controlled approval artifact before it is connected to project systems.',
  },
  {
    action: 'web3.transfer',
    title: 'Web3 Transfer',
    domain: 'web3',
    capabilities: ['transact', 'govern', 'record'],
    connectorKey: 'finance_connector',
    maturity: 'stub',
    liveMode: 'disabled',
    risk: 'high',
    approvalRequired: true,
    supportsDryRun: true,
    supportsRollback: false,
    inputRequired: ['chain', 'to', 'amount'],
    outputContract: ['notImplemented'],
    productionNote: 'Do not expose as live execution; OneClaw currently treats most Web3 writes as not implemented.',
  },
];

export function listOneClawCapabilities() {
  return oneClawCapabilityRegistry;
}

export function getOneClawCapability(action: string) {
  return oneClawCapabilityRegistry.find((capability) => capability.action === action) || null;
}

export function summarizeOneClawProductionReadiness() {
  return oneClawCapabilityRegistry.reduce<Record<string, number>>((summary, capability) => {
    summary[capability.maturity] = (summary[capability.maturity] || 0) + 1;
    return summary;
  }, {});
}
